print("\n")
print("\n")
print("Soy un cientifico matemático que estudia fisica cuantica, fisica, más fisica, y sumas y restas.")
print("*Se acomoda las gafas*")
print("Voy a hacer un calculo muy grande.")
print("Entonces si divido esto y multiplico lo otro.")
print("\n")
print("Por lo tanto 2,23 por 89 entre 56 y luego pongo el 4,353 porciento del resultado da igual a:")
print("\n")
print(2.23 * 89 / 56 % 4.353)
print("\n")
print("\n")
print("Perfección.")
