print("soy un cientifico matemático que estudia fisica cuantica, fisica, más fisica, y sumas y restas.")
print("*se acomoda las gafas*")
print("voy a hacer un calculo muy grando")
print("entonces si divido esto y multiplico lo otro.")
print("\n")
print("por lo tanto 2,23 por 89 entre 56 y luego pongo el 4,353 porciento da igual a:")
print("\n")
print(2.23 * 89 / 56 % 4.353)
print("\n")
print("\n")
print("Perfección.")
