print("soy un cientifico matemático que estudia\n fisica cuantica, fisica, más fisica, y sumas y restas, las teorias")
print("*se acomoda las gafas*")
print("entonces si divido esto y multiplico lo otro")
print("2,23 por 89 entre 56 y luego pongo el 4,353 porciento da igual a:")
print(2,23 * 89 / 56 % 4,353)
print("perfección.")
